version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy

  # Your application
  app:
    build: .
    ports:
      - "8080:8080"  # Adjust the port as per your application
    restart: always
    depends_on:
      - postgres