apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-deployment
  labels:
    app: academy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: academy
  template:
    metadata:
      labels:
        app: academy
    spec:
      containers:
        - name: app
          image: test-hibernate-with-clean:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgresdb
            - name: POSTGRES_USER
              value: academy
            - name: POSTGRES_PASSWORD
              value: academy