name: Docker Tag and Push Image
inputs:
  username:
    description: "Docker Hub Username"
    required: true
  image_name:
    description: "Name of the Docker image"
    required: true
description: Tag and Push Docker Image
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        IMAGE_NAME_TO_PUSH=${{ inputs.username }}/${{ inputs.image_name }}
        docker tag ${{ inputs.image_name }} $IMAGE_NAME_TO_PUSH
        docker push $IMAGE_NAME_TO_PUSH