name: Docker Tag and Push Image
inputs:
  image_name:
    description: "Name of the Docker image"
    required: true
description: Tag and Push Docker Image
runs:
  using: composite
  steps:
    - shell: bash
      run: docker tag ${{ inputs.image_name }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}