name: Docker Tag and Push Image
inputs:
  username:
    description: "Docker Hub Username"
    required: true
  image_name:
    description: "Name of the Docker image"
    required: true
description: Tag and Push Docker Image
runs:
  using: composite
  steps:
    - shell: bash
      run: docker tag ${{ inputs.image_name }} ${{ inputs.username }}/${{ inputs.image_name }}