apiVersion: v1
kind: ConfigMap
metadata:
  name: academy-configmap
data:
  fruit.name.uppercase.force: "%FORCE_UPPERCASE%"
  quarkus.datasource.jdbc.url: "jdbc:postgresql://postgres-service:5432/postgres"