name: Docker Image CI

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Build
      uses: antonio-pinheiro-wtc/teste/.github/actions/docker_build@main
      with:
        path_dockerfile: .
        image_name: academy

    - name: Apply Secret
      uses: antonio-pinheiro-wtc/teste/.github/actions/apply@main
      with:
        namespace: academy
        filename: kubernetes/secret.yaml