name: Docker Image CI

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: academy
          POSTGRES_PASSWORD: academy
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
   

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v4
      if: ${{ !env.ACT }}
      with:
        distribution: 'corretto' # See 'Supported distributions' for available options
        java-version: '17'

#    - name: Docker Build
#      uses: antonio-pinheiro-wtc/teste/.github/actions/docker_build@main
#      with:
#        path_dockerfile: Dockerfile
#        image_name: academy

    - name: Login to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

#    - name: Docker Push
#      uses: antonio-pinheiro-wtc/teste/.github/actions/push@main
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        image_name: ${{ env.DOCKER_IMAGE_NAME }}

    - name: Create PostgreSQL container
      uses: antonio-pinheiro-wtc/teste/.github/actions/postgres-container@main
      with:
        name: actions-postgres
        port: 41200
        username: academy
        password: academy

    - name: Run Quarkus Tests
      run:  |
        if [[ "${ACT}" == "true" ]]; then
          mvn test -Dquarkus.datasource.jdbc.url=jdbc:postgresql://localhost:41200/postgres
        else
          mvn test
        fi

    - name: Replace variables on kubernetes templates
      if: ${{ env.ACT }}
      env:
        database_username: ${{ secrets.DATABASE_USERNAME }}
        database_password: ${{ secrets.DATABASE_PASSWORD }}
      run: |
        DOCKER_IMAGE_NAME=academy:1712349130
        
        database_username_base64=$(echo -n "$database_username" | base64)
        database_password_base64=$(echo -n "$database_password" | base64)
        
        sed -i'' -e "s/%DATABASE_USERNAME%/$database_username_base64/g" kubernetes-postgres/secret.yaml
        sed -i'' -e "s/%DATABASE_PASSWORD%/$database_password_base64/g" kubernetes-postgres/secret.yaml
        
        sed -i'' -e "s/%IMAGE_PLACEHOLDER%/$DOCKER_IMAGE_NAME/g" kubernetes/deployment.yaml
        sed -i'' -e "s/%DATABASE_USERNAME%/$database_username_base64/g" kubernetes/secret.yaml
        sed -i'' -e "s/%DATABASE_PASSWORD%/$database_password_base64/g" kubernetes/secret.yaml
        
        kubectl apply -f kubernetes-postgres -n academy
        
        kubectl wait --for=condition=available deployment/postgres --timeout 180 -n academy
        
        
        kubectl apply -f kubernetes -n academy

#    - name: Apply Deployment
#      if: ${{ env.ACT }}
#      run: |
#        sed -i'' -e "s/%IMAGE_PLACEHOLDER%/$DOCKER_IMAGE_NAME/g" kubernetes/deployment.yaml
#        kubectl apply -f kubernetes/deployment.yaml -n academy

#    - name: Apply Secret
#      if: ${{ env.ACT }}
#      uses: antonio-pinheiro-wtc/teste/.github/actions/apply@main
#      with:
#       namespace: academy
#        filename: kubernetes/secret.yaml