name: Docker Image CI

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: academy
          POSTGRES_PASSWORD: academy
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
   

    steps:
    - uses: actions/checkout@v3

    - name: Echo the Postgres service ID / Network / Ports
      run: |
        echo "id: ${{ job.services.postgres.id }}"
        echo "network: ${{ job.services.postgres.network }}"
        echo "ports: ${{ job.services.postgres.ports }}"
        docker ps
      

#    - name: Docker Build
#      uses: antonio-pinheiro-wtc/teste/.github/actions/docker_build@main
#      with:
#        path_dockerfile: Dockerfile
#        image_name: academy
    - name: Run Quarkus Tests
      run: psql -h postgres -U academy -d postgres

    - name: Apply Secret
      uses: antonio-pinheiro-wtc/teste/.github/actions/apply@main
      with:
        namespace: academy
        filename: kubernetes/secret.yaml