name: Docker Image CI

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: academy
          POSTGRES_PASSWORD: academy
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
   

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v4
      if: ${{ !env.ACT }}
      with:
        distribution: 'corretto' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Docker Build
      uses: antonio-pinheiro-wtc/teste/.github/actions/docker_build@main
      with:
        path_dockerfile: Dockerfile
        image_name: academy

    - name: Login to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Push
      uses: antonio-pinheiro-wtc/teste/.github/actions/push@main
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        image_name: ${{ env.DOCKER_IMAGE_NAME }}

    - name: Run Quarkus Tests
      run:  mvn test

    - name: Apply Deployment
      if: ${{ env.ACT }}
      run: |
        sed -i'' -e "s/%IMAGE_PLACEHOLDER%/$DOCKER_IMAGE_NAME/g" kubernetes/deployment.yaml
        kubectl apply -f kubernetes/deployment.yaml -n academy

    - name: Apply Secret
      if: ${{ env.ACT }}
      uses: antonio-pinheiro-wtc/teste/.github/actions/apply@main
      with:
        namespace: academy
        filename: kubernetes/secret.yaml