name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Apply Secret
      uses: antonio-pinheiro-wtc/teste/.github/actions/apply.yml@main
      with:
        namespace: academy
        filename: kubernetes/secret.yaml