name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      UpperCaseForce:
        required: false
        type: choice
        description: 'Force uppercase'
        default: 'false'
        options:
          - 'true'
          - 'false'

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: academy
          POSTGRES_PASSWORD: academy
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
   

    steps:
    - uses: actions/checkout@v3

    - run: echo "${{ github.event.inputs.UpperCaseForce }}"

    - uses: actions/setup-java@v4
      if: ${{ !env.ACT }}
      with:
        distribution: 'corretto' # See 'Supported distributions' for available options
        java-version: '17'

#    - name: Docker Build
#      uses: antonio-pinheiro-wtc/teste/.github/actions/docker_build@main
#      with:
#        path_dockerfile: Dockerfile
#        image_name: academy

#    - name: Login to Docker Hub
#      uses: docker/login-action@v3.1.0
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

#    - name: Docker Push
#      uses: antonio-pinheiro-wtc/teste/.github/actions/push@main
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        image_name: ${{ env.DOCKER_IMAGE_NAME }}

    - name: Create PostgreSQL container
      if: ${{ env.ACT }}
      uses: antonio-pinheiro-wtc/teste/.github/actions/postgres-container@main
      with:
        name: actions-postgres
        port: 41200
        username: academy
        password: academy

#    - name: Run Quarkus Tests
#      run:  |
#        if [[ "${ACT}" == "true" ]]; then
#          mvn test -Dquarkus.datasource.jdbc.url=jdbc:postgresql://localhost:41200/postgres
#        else
#          mvn test
#        fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - uses: actions/checkout@v3

    - name: Replace variables on kubernetes templates
      env:
        upper_case_force: ${{ github.event.inputs.UpperCaseForce }}
        database_username: ${{ secrets.DATABASE_USERNAME }}
        database_password: ${{ secrets.DATABASE_PASSWORD }}
      run: |
        DOCKER_REPOSITORY="antoniopinheiro798"
        DOCKER_IMAGE_NAME="academy:1712527216" 
        
        database_username_base64=$(echo -n "$database_username" | base64)
        database_password_base64=$(echo -n "$database_password" | base64)
        
        sed -i'' -e "s/%DATABASE_USERNAME%/$database_username_base64/g" kubernetes-postgres/secret.yaml
        sed -i'' -e "s/%DATABASE_PASSWORD%/$database_password_base64/g" kubernetes-postgres/secret.yaml

        sed -i'' -e "s/%REPOSITORY_PLACEHOLDER%/$DOCKER_REPOSITORY/g" kubernetes/deployment.yaml
        sed -i'' -e "s/%IMAGE_PLACEHOLDER%/$DOCKER_IMAGE_NAME/g" kubernetes/deployment.yaml
        
        sed -i'' -e "s/%DATABASE_USERNAME%/$database_username_base64/g" kubernetes/secret.yaml
        sed -i'' -e "s/%DATABASE_PASSWORD%/$database_password_base64/g" kubernetes/secret.yaml
        sed -i'' -e "s/%FORCE_UPPERCASE%/$upper_case_force/g" kubernetes/configmap.yaml
        cat kubernetes/configmap.yaml
        env
    - name: Apply Deployment of PostgreSQL and the Application
      if: ${{ env.ACT }}
      run: |
        kubectl apply -f kubernetes-postgres -n academy
        kubectl wait --for=condition=available deployment/postgres --timeout=60s -n academy  
        kubectl apply -f kubernetes -n academy